### ISSUE TITLE
Create the landing page/home for web app 

### ISSUE THREAD

**Issue by palrohitg** [palrohitg/reviewscrapper#3]
Landing page include the nav-bar and form an the center and u can add any background image to look the home page more appealing , also your anything that make the home page more cool . Creativity is welcome !!!

**Comment by Tejas1510** [comment]
I would like to work on this

**Comment by palrohitg** [comment]
@Tejas1510  can you express your idea what are thing you are going to add.

**Comment by Tejas1510** [comment]
Sir I wish to make the complete homepage in Bootstrap with navbar at the top with a jumbotron at the upper part. Then as mentioned by you I would add a form as required according to the need and a footer at the bottom. If any more features like a carousel, modal, or anything is required we can even work on that.

**Comment by palrohitg** [comment]
@Tejas1510  that great . The form is  one search bar as input and button. According to the product input it going to scrap all the review from the website which might take some delay. So it possible from your end to some kind of progress bar is going to show after clicking on the search button.

**Comment by palrohitg** [comment]
@Tejas1510  feel free add the issue if you some in your mind

**Comment by Tejas1510** [comment]
Ok Sir
Thanks for the response

**Comment by palrohitg** [comment]
you can fork the repo and start working on the issue  asap. let me if you can stuck any where related to local setup and anything.

**Comment by Tejas1510** [comment]
Yes sure

**Comment by build-with-rishi** [comment]
I've forked this repo and created a separate page (home.html) including all your base elements needed from index file. 
Please check it and tell me if it's okay!
