### ISSUE TITLE
add one section for the contributor where we can list the details of the contributor in Readme

### ISSUE THREAD

**Issue by palrohitg** [palrohitg/reviewscrapper#4]
Add the contributor list in the readme and labels like no of forks and view etc

**Comment by moingshaikh** [comment]
Hi @palrohitg,

If you prefer, I can help here and integrate a GitHub tool (https://allcontributors.org/) that recognizes and lists contributors of the project in the README.md file.

Please let this sounds good to you.

Thanks!

**Comment by palrohitg** [comment]
@moingshaikh  ya sure, you can work upon this.

**Comment by build-with-rishi** [comment]
I've created the layout in about.html file to support a short description of contributors and their social profile links. You can check it!

Regards!
